//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEDI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indirimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indirimler()
        {
            this.Odemes = new HashSet<Odeme>();
        }
    
        public int IndirimID { get; set; }
        public string IndirimAdi { get; set; }
        public decimal Oran { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> UrunID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odeme> Odemes { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
