//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEDI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KEDIDBEntities : DbContext
    {
        public KEDIDBEntities()
            : base("name=KEDIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Indirimler> Indirimlers { get; set; }
        public virtual DbSet<Loglar> Loglars { get; set; }
        public virtual DbSet<Masalar> Masalars { get; set; }
        public virtual DbSet<Odeme> Odemes { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Salonlar> Salonlars { get; set; }
        public virtual DbSet<Siparisler> Siparislers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<Yetkiler> Yetkilers { get; set; }
    }
}
