//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEDI_v_0._5._0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisLog
    {
        public int LogID { get; set; }
        public int KullaniciID { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
