//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KEDI_v_0._5._0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Printer
    {
        public int PrinterID { get; set; }
        public string PrinterName { get; set; }
        public string PrinterIP { get; set; }
        public Nullable<bool> Online { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool CancelProd { get; set; }
        public bool Report { get; set; }
        public bool Product { get; set; }
        public bool AccountPrint { get; set; }
    }
}
